#-----------------------------------------------------------------------------
# GNUmakefile used to check-out special Miriad doc files.
#
# Original: 2007/11/28, Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
