#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad source files.
#
# Original: 2009/01/16, Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
