#! /bin/csh
#-----------------------------------------------------------------------------
# $Id$
#-----------------------------------------------------------------------------

  set DIR = $MIR/at_friends
  source  /u/support/BOOK/BOOKENV.CSH

# Generate a list of known users.
  rm -f bookings.users
  awk '{s = substr($1,0,1); if (s >= "a" && s <= "z") print $1;}' \
    $DIR/users.txt | sort -u > bookings.users

# Generate a list of users with bookings.
  rm -f bookings.current
  touch bookings.current
  foreach file ($BOOK/DATA/*.DIARY)
    awk 'BEGIN {arm = 0} \
               {if (arm && $1 != "#" && $4 != "" && $4 != ";") print $4} \
         $1 == ";" {arm = 1}' $file | sed -e 's/;//g' >> bookings.current
  end

# Any new users?
  rm -f bookings.newusers
  sort -u bookings.current | comm -1 -3 bookings.users - > bookings.newusers

  cat /dev/null > bookings.mail

  if (! -z bookings.newusers) then
    foreach user (`cat bookings.newusers`)
      grep -h $user $BOOK/DATA/*.DIARY >> bookings.mail
    end

    echo >> bookings.mail
  endif

# Append the visitor schedule.
  setenv SCHEDULE=http://www.atnf.csiro.au/people/visitor_schedule.html
  lynx -dump -width=110 "$SCHEDULE" | \
    sed -n -e '{/staff/d;s/^        //p;}' >> bookings.mail

# Mail it to interested parties.
  mail -s "New users with bookings" \
    at_friends@atnf.csiro.au,mirmgr@atnf.csiro.au, < bookings.mail
