\chapter{Bibliography}



Bracewell, R.N., The Fourier Transform and its Applications

Briggs D., ??. \htmladdnormallink{``??''}
{http://www.aoc.nrao.edu/ftp/dissertations/dbriggs/diss.html}
PhD thesis
\begin{latexonly}
\verb+http://www.aoc.nrao.edu/ftp/dissertations/dbriggs/diss.html+
\end{latexonly}.

Christiansen, W.N., H\"ogbom, J.A., Radiotelescopes.

Clark B.G., 1980, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1980A\%26A....89..377C}
{\it Astron. Astrophys.} 26, 89.

Cornwell T.J., 1983, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1983A\%26A...121..281C}
{\it Astron. Astrophys.}, 121, 281.

Cornwell T.J., 1988
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1988A\%26A...202..316C}
{\it Astron. Astrophys.}, 202, 316.

Cornwell T.J., Holdaway M., Uson J., 1993
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1993A\%26A...271..697C}
{\it Astron. Astrophys.}, 271, 697.

Cornwell T.J., Uson J., Haddad ??, 1992, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1992A\%26A...258..583C$
{\it Astron. Astrophys.}, 258, 583.

Frater R.H. ed. (1992)
Journal of Electrical and Electronics Engineering, Australia: Special
Issue}{http://www.narrabri.atnf.csiro.au/observing/iree.pdf}
-- The Australia Telescope, 12.
\begin{latexonly}
\verb+http://www.narrabri.atnf.csiro.au/observing/iree.pdf+
\end{latexonly}

Greisen E., ?? \htmladdnormallink{``{\it Non-linear coordinate systems in \aips}''}
{ftp://ftp.aoc.nrao.edu/pub/software/aips/TEXT/PUBL/AIPSMEMO27.PS}
\aips\ memo No. 27
\begin{latexonly}
ftp://ftp.aoc.nrao.edu/pub/software/aips/TEXT/PUBL/AIPSMEMO27.PS
\end{latexonly}.

Hamaker J., Bregman J., Sault R.J., 1996,
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1996A\%26AS..117..137H}
{\it Astron. Astrophys.} 117, 137.

H\"ogbom J., 1974, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1974A\%26AS...15..417H}
{\it Astron. Astrophys. Suppl.} 15, 417.

Killeen N.E.B., 199??, 
\htmladdnormallink{``??''}
{http://www.atnf.csiro.au/observers/memos/d98b8b\~{}1.pdf} AT Memo 39.3/057
\begin{latexonly}
\verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Killeen N.E.B., Lo K.Y., Crutcher R., 1992,
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1992ApJ...385..585K}
{\it Astrophys. J.}, 385, 585.

Kraus, J.D., Radio Astronomy

Reynolds J.E., ??, 
\htmladdnormallink{``A revised flux scale for the AT
Compact Array''}{http://www.atnf.csiro.au/observers/memos/d96783\~{}1.pdf}
AT Memo 39.3/040
\begin{latexonly}
\verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Rohlfs, K., Wilson, T.L., Tools of Radio Astronomy.

Sault R.J., 199??, \htmladdnormallink{``Some simulations of
self-calibration for the AT''}
{http://www.atnf.csiro.au/observers/memos/d96f87~{}1.pdf} AT Memo 39.3/058
\begin{latexonly}
\verb+{http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Sault R.J., 1994, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1994A\%26AS..107...55S}
{\it Astron. Astrophys. Suppl.}, 107, 55.

Sault R.J., Noordam J.E., 1995, 
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1995A\%26AS..109..593S}
{\it Astron. Astrophys. Suppl.}, 109, 539.

Sault R.J., Staveley-Smith L., Brouw W.N., 1996,
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1996A\%26AS..120..375S}
{\it Astron. \& Astrophys. Suppl.}, 120, 376.

Sault R.J., Bock D., 1999
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1999A\&AS..139..387S}  
{\it Astron Astrophys. Suppl.}, 139, 387.

Sault R.J., 2003,``ATCA flux density scale at 12mm''
\htmladdnormallink{http://www.narrabri.atnf.csiro.au/calibrators/data/1934-638/1934_12mm.pdf}
{http://www.narrabri.atnf.csiro.au/calibrators/data/1934-638/1934_12mm.pdf}
\begin{latexonly}
\verb+http://www.narrabri.atnf.csiro.au/calibrators/data/1934-638/1934_12mm.pdf+
\end{latexonly}

Sault R.J., Killeen N.E.B., Kesteven, M.J., 199??
\htmladdnormallink{``AT Polarisation Calibration''}
{http://www.atnf.csiro.au/observers/memos/d97b7f\~{}1.pdf} AT Memo 39.3/015
\begin{latexonly}
\verb+http://www.atnf.csiro.au/observers/memos/+
\end{latexonly}.

Sault R.J., Hamaker J., Bregman J., 1996,
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1996A\%26AS..117..149S}
{\it Astron. Astrophys.}, 117, 149.

Sault R.J., Killeen N.E.B., Zmuidzinas J., Loushin R., 1990,
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1990ApJS...74..437S}
{\it Astrophys. J. Suppl.}, 74, 437.

Sault R.J., Teuben P.J.,
Wright M.C.H., 1995, \htmladdnormallink{``A retrospective view of Miriad''}
{http://www.stsci.edu/stsci/meetings/adassIV/saultr.html}
in \htmladdnormallink{{\it Astronomical Data Analysis Software and
Systems IV}}{http://www.stsci.edu/stsci/meetings/adassIV},
ed. R. Shaw, H.E. Payne, J.J.E. Hayes, ASP Conf. Ser., 77, 433-436.

Sault R.J., Wieringa M.H., 1994, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1994A\%26AS..108..585S}
{\it Astron. Astrophys. Suppl.}, 108, 585.

Stanimirovic S., 2002, 
\htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=2002sdra.conf..375S}   
ASP Conf. Series, 278, p 375.

Steer ??, Dewdney ??, Ito ??, 1984, \htmladdnormallink{``??''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1984A\%26A...137..159S}
{\it Astron. Astrophys.}, 137, 159

Subrahmanyan R., 2005,
\htmladdnormallink{``Photogrammetric measurement of the gravity deformation
in a Cassegrain antenna''}
{http://ieeexplore.ieee.org/iel5/8/32084/01492610.pdf?tp=&arnumber=1492610&isnumber=32084}
{\it IEEE Trans Antennas Propogation}, 53, 2590-2596.

Taylor G.B., Carilli C.L., Perley R., eds,
Synthesis Imaging in Radio Astronomy II,
Astronomical Society of the Pacific Conference Series Volume 180.

Thompson A.R., Moran J.M., Swenson G.W., Interferometry and Synthesis in Radio Astronomy.

Ulich, B.L.\ 1980, \htmladdnormallink{``Improved correction for millimeter-wavelength atmospheric attenuation''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1980ApL....21...21U},
{\it Astrophys. Letters}, 21, 21.

van Hoerner S., 1967, 
\htmladdnormallink{``Design of large steerable antennas''}
{http://adsabs.harvard.edu/cgi-bin/nph-bib_query?bibcode=1967AJ.....72...35V}
{\it Astron. J.}, 72, 35.

Wieringa M.H., Kesteven, M.J, 1992, \htmladdnormallink{``Measurements of the ATCA primary beam''}
{http://www.atnf.csiro.au/observers/memos/d97f7b\~{}1.pdf}, AT Memo 39.3/024
begin{latexonly}
\verb+http://www.atnf.csiro.au/observers/memos/+
begin{latexonly}.
\end{itemize}
