#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: Buildtitlepage [id]
#-----------------------------------------------------------------------------
# Generate the front page of the Miriad User or Programmer manual in
# encapsulated PostScript.
#
# Implemented as a shell script in order to capture the date and to handle
# both guides.  The id argument should be specified as User (default) or
# Programmer.
#
# $Id$
#-----------------------------------------------------------------------------

  if [ $# -lt 1 ]
  then
    ID=User
  else
    ID=$1
  fi

  DATE=`date +"%d %h %Y"`
  echo "$ID Guide title page date is $DATE."

cat << EOF > titlepage.eps
%!PS
/TM 820 def
/BM -70 def
/LM -20 def
/RM 630 def

/newline {
  currentpoint 13 sub
  exch pop LM
  exch moveto
} def

/nlIfNec {currentpoint pop RM gt {newline}if} def

/done? {currentpoint exch pop BM lt} def

/fillpage {
  /strg exch def
  { {pop pop nlIfNec} strg kshow
     done? {exit} if
  } loop
} def

/Times-Bold findfont 10 scalefont setfont
LM TM moveto
0.6 setgray
( Miriad ) fillpage

/Times-Roman findfont 50 scalefont setfont
RM LM sub
(Miriad)stringwidth pop sub
2 div 500 moveto
0 setgray
(Miriad)show

/Times-Roman findfont 20 scalefont setfont
RM LM sub (Multichannel Image Reconstruction,) stringwidth pop sub
2 div 460 moveto
(Multichannel Image Reconstruction,)show
RM LM sub (Image Analysis and Display) stringwidth pop sub
2 div 430 moveto
(Image Analysis and Display)show

/Times-Roman findfont 50 scalefont setfont
RM LM sub ($ID Guide) stringwidth pop sub
2 div 360 moveto
($ID Guide)show

/Times-Roman findfont 20 scalefont setfont
RM LM sub (Bob Sault and Neil Killeen) stringwidth pop sub
2 div 130 moveto
(Bob Sault and Neil Killeen) show
RM LM sub ($DATE) stringwidth pop sub
2 div 100 moveto
($DATE) show
RM LM sub (See http://www.atnf.csiro.au/computing/software/miriad)
stringwidth pop sub 2 div 20 sub 50 moveto
(See http://www.atnf.csiro.au/computing/software/miriad) show
EOF
