#-----------------------------------------------------------------------------
# GNUmakefile used to check out miscellaneous ATNF system management files.
#
# Original: 2006/11/29, Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
