#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: rsynx [-d] [Mopra] [Narrabri] [Parkes]
#-----------------------------------------------------------------------------
# Run rsync to update /nfs/atapplic/miriad/... at Mopra, Narrabri, and Parkes.
# It is assumed that ssh access for the destination host has been set up on
# the source host. You need the remote host in .ssh/known_hosts and you must
# add id_rsa.pub to .ssh/authorized_keys on the other end.
#
# Original: 2011/08/09 MRC
#-----------------------------------------------------------------------------
  if [ "$LOGNAME" != mirmgr ]
  then
    printf "rsynx is expected to be run by mirmgr.\n" 1>&2
    exit 1
  fi

  DELIM="--------------------------------------------"

  DRYRUN=
  SITES=

  while [ "$#" -gt 0 ]
  do
    case $1 in
    -d)
      DRYRUN="--dry-run"
      printf "\nWARNING: Doing a dry-run only.\n"
      ;;
    M*)
      SITES="$SITES Mopra"
      ;;
    N*)
      SITES="$SITES Narrabri"
      ;;
    P*)
      SITES="$SITES Parkes"
      ;;
    esac

    [ "$2" = "" ] && break

    shift
  done

  [ "$SITES" ] || SITES="Mopra Narrabri Parkes"

  # For remote hosts running Linux.
  RSYNCSSH="ssh -i ${HOME}/.ssh/id_dsa"
  RSYNCL="/usr/bin/rsync $DRYRUN --verbose --archive --delete --compress \
           --rsync-path=/usr/bin/rsync"

  # For remote hosts running Solaris.
  #RSYNCSSH="ssh -1 -i ${HOME}/.ssh/identity"
  RSYNCS="/usr/bin/rsync $DRYRUN --verbose --archive --delete --compress \
           --rsync-path=/usr/local/bin/rsync"

  SRC=/nfs/atapplic/miriad

  date "+%n%a %Y/%m/%d %T %Z $DELIM%n"

  for SITE in $SITES
  do
    case "$SITE" in
        Mopra)    DST=warrum;  RSYNC_CMD="$RSYNCL" ;;
        Narrabri) DST=zephir;  RSYNC_CMD="$RSYNCL" ;;
        Parkes)   DST=sagitta; RSYNC_CMD="$RSYNCS" ;;
    esac
    DST="${DST}:/nfs/atapplic/"

    printf "$SITE: Sending $SRC to $DST\n"
    $RSYNC_CMD  -e "$RSYNCSSH" \
      --exclude=.mirsync/ \
      --exclude=etc/rsynx.log \
      $SRC $DST

    date "+%n%a %Y/%m/%d %T %Z $DELIM%n"
  done

  [ "$DRYRUN" ] && printf "\nWARNING: That was a dry run only.\n"

  exit 0
