#!/bin/sh
#-----------------------------------------------------------------------------
# Usage: updatem
#-----------------------------------------------------------------------------
# Run rsync to update the local copy of the Miriad source code cached in
# /nfs/atapplic/miriad/, rebuild it, then rsync the binaries back to the true
# Miriad installation on atlas:/nfs/atapplic/miriad/.
#
# This is required because NFS has not been set up for PowerPC (crab) or Intel
# (cancer) Macs.  The rsyncs assume that password-less ssh protocol version 1
# (rsa1) access to atlas from the Mac (crab or cancer) has been set up for
# mirmgr.
#
# Original: 2006/10/19 MRC
# $Id$
#-----------------------------------------------------------------------------

  trap 'exit 1' 1 2 3 15

  cd /nfs/atapplic/miriad/ || exit 1
  . MIRRC.sh

  case $MIRARCH in
  darwin_*)
    # OK.
    ;;
  *)
    echo "updatem: This script is only intended for Darwin platforms." 1>&2
    exit 1
    ;;
  esac

  date "+Miriad $MIRARCH update started on %a %Y/%m/%d %T"
  echo

  RSYNC="/usr/bin/rsync -v --archive --delete"
  RSYNC="$RSYNC --delete-excluded --exclude=RCS"
  RSYNC="$RSYNC --rsh=ssh --rsync-path=/usr/local/bin/rsync"

  echo "Fetching modified Miriad source files from atlas..."

  FILES="DISCLAIMER GNUmakedefs GNUmakefile INSTALL.html MIRRC MIRRC.sh"
  FILES="$FILES configure configure.ac"
  FILES="$FILES progguide.ps progguide_US.ps.gz"
  FILES="$FILES userguide.ps userguide_US.ps.gz"

  DIRS="cat config etc guides inc linpack prog scripts spec subs tests tools"

  for i in $FILES $DIRS
  do
    SRC="$SRC /nfs/atapplic/miriad/$i"
  done

  $RSYNC atlas:"$SRC" .

  # The Programmer and User Guides are not compiled on the Macs.
  DIRS="html/progguide html/userguide"
  SRC=

  for i in $DIRS
  do
    SRC="$SRC /nfs/atapplic/miriad/$i"
  done

  $RSYNC atlas:"$SRC" html


# Now rebuild.
  echo
  gmake MIRATNF=1 2>&1 | tee $MIRARCH/gmake.log


# Send the results back.
  echo
  echo
  echo "Sending $MIRARCH binaries back to atlas..."
  $RSYNC $MIRARCH/ atlas:/nfs/atapplic/miriad/$MIRARCH/

  echo
  echo
  date "+Miriad $MIRARCH update finished on %a %Y/%m/%d %T"
