#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad catalogue files.
#
# Original: 2009/02/09, Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
