#-----------------------------------------------------------------------------
# GNUmakefile used to check-out Miriad include files.
#
# Original: 2006/09/19, Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
