#! /bin/csh -f
#--
#
#* mirversion - Give the version of Miriad.
#& rjs
#: user utility
#+
#  Usage: mirversion
#--


  if ( -r $MIR/changes.txt ) \
    set hostupdate = `grep '^[0-9]' $MIR/changes.txt|tail -1|awk '{print $1}'`
  else
    set hostupdate = "unknown"
  endif

  echo "Miriad version date: $hostupdate"
