#-----------------------------------------------------------------------------
# GNUmakefile used to checkout and/or install architecture-specific Miriad
# scripts.
#
# Original: 2011/03/23, Mark Calabretta, ATNF
# $Id$
#-----------------------------------------------------------------------------
# Get common makefile variables and rules (defines everything needed here).
include $(MIR)/GNUmakedefs
